# Generated by Django 5.0.6 on 2024-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='main_tag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='short_discription',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
