# Generated by Django 5.0.6 on 2024-08-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aimodel_img_alter_chatgroup_ai_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='use_case',
            new_name='best_use_case',
        ),
        migrations.RenameField(
            model_name='aimodel',
            old_name='img',
            new_name='img_hero',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='img_icon',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='senario_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='senario_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='senario_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
